const pm2_jlist = {
    "pid": 105581,
    "name": "raven-stone2_3000",
    "pm2_env": {
        "exit_code": 0,
        "versioning": null,
        "version": "N/A",
        "unstable_restarts": 0,
        "restart_time": 28,
        "pm_id": 0,
        "created_at": 1701076620300,
        "axm_dynamic": {},
        "axm_options": {},
        "axm_monitor": {},
        "axm_actions": [],
        "pm_uptime": 1701076620424,
        "status": "online",
        "unique_id": "6abc5459-f99d-423f-8138-b6d86df7597c",
        "PM2_HOME": "/root/.pm2",
        "PM2_INTERACTOR_PROCESSING": "true",
        "PM2_USAGE": "CLI",
        "OLDPWD": "/etc/nginx/sites-enabled",
        "_": "/root/.nvm/versions/node/v19.9.0/bin/pm2",
        "SSH_TTY": "/dev/pts/0",
        "NVM_BIN": "/root/.nvm/versions/node/v19.9.0/bin",
        "PATH": "/root/.nvm/versions/node/v19.9.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "LC_ALL": "en_US.UTF-8",
        "SSH_CLIENT": "223.255.228.93 23747 22",
        "XDG_RUNTIME_DIR": "/run/user/0",
        "LC_CTYPE": "UTF-8",
        "XDG_SESSION_ID": "5",
        "NVM_CD_FLAGS": "",
        "SHLVL": "1",
        "USER": "root",
        "TERM": "xterm-256color",
        "XDG_SESSION_CLASS": "user",
        "NVM_DIR": "/root/.nvm",
        "SSH_CONNECTION": "223.255.228.93 23747 85.31.224.193 22",
        "LANG": "en_US.UTF-8",
        "HOME": "/root",
        "MOTD_SHOWN": "pam",
        "XDG_SESSION_TYPE": "tty",
        "LOGNAME": "root",
        "PWD": "/root/projects/raven-stone2",
        "LANGUAGE": "en_US.UTF-8",
        "NVM_INC": "/root/.nvm/versions/node/v19.9.0/include/node",
        "SHELL": "/bin/bash",
        "NODE_APP_INSTANCE": 0,
        "vizion_running": false,
        "km_link": false,
        "pm_pid_path": "/root/.pm2/pids/raven-stone2-0.pid",
        "pm_err_log_path": "/root/.pm2/logs/raven-stone2-3000-error.log",
        "pm_out_log_path": "/root/.pm2/logs/raven-stone2-3000-out.log",
        "instances": 1,
        "exec_mode": "fork_mode",
        "exec_interpreter": "none",
        "pm_cwd": "/root/projects/raven-stone2",
        "pm_exec_path": "/usr/bin/bash",
        "node_args": [],
        "name": "raven-stone2_3000",
        "filter_env": [],
        "namespace": "default",
        "args": [
            "-c",
            "yarn start -p 3000"
        ],
        "env": {
            "unique_id": "6abc5459-f99d-423f-8138-b6d86df7597c",
            "raven-stone2_3000": {},
            "PM2_HOME": "/root/.pm2",
            "PM2_INTERACTOR_PROCESSING": "true",
            "PM2_USAGE": "CLI",
            "OLDPWD": "/etc/nginx/sites-enabled",
            "_": "/root/.nvm/versions/node/v19.9.0/bin/pm2",
            "SSH_TTY": "/dev/pts/0",
            "NVM_BIN": "/root/.nvm/versions/node/v19.9.0/bin",
            "PATH": "/root/.nvm/versions/node/v19.9.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "LC_ALL": "en_US.UTF-8",
            "SSH_CLIENT": "223.255.228.93 23747 22",
            "XDG_RUNTIME_DIR": "/run/user/0",
            "LC_CTYPE": "UTF-8",
            "XDG_SESSION_ID": "5",
            "NVM_CD_FLAGS": "",
            "SHLVL": "1",
            "USER": "root",
            "TERM": "xterm-256color",
            "XDG_SESSION_CLASS": "user",
            "NVM_DIR": "/root/.nvm",
            "SSH_CONNECTION": "223.255.228.93 23747 85.31.224.193 22",
            "LANG": "en_US.UTF-8",
            "HOME": "/root",
            "MOTD_SHOWN": "pam",
            "XDG_SESSION_TYPE": "tty",
            "LOGNAME": "root",
            "PWD": "/root/projects/raven-stone2",
            "LANGUAGE": "en_US.UTF-8",
            "NVM_INC": "/root/.nvm/versions/node/v19.9.0/include/node",
            "SHELL": "/bin/bash"
        },
        "merge_logs": true,
        "vizion": true,
        "autorestart": true,
        "watch": false,
        "instance_var": "NODE_APP_INSTANCE",
        "pmx": true,
        "automation": true,
        "treekill": true,
        "username": "root",
        "windowsHide": true,
        "kill_retry_time": 100,
        "prev_restart_delay": 0
    },
    "pm_id": 0,
    "monit": {
        "memory": 88076288,
        "cpu": 0
    }
}

module.exports = pm2_jlist